language: go
sudo: false
go:
  - 1.6.2
  - tip
env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1
before_install:
  - go get -u github.com/jteeuwen/go-bindata/...
script:
  - go generate
  - go test
install:
  - go install
